_wandb:
    value:
        cli_version: 0.21.1
        e:
            yjtqtwp722ic33neb30i07b9m17vjjhm:
                codePath: trainers\train_uctransnet2d.py
                codePathLocal: train_uctransnet2d.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "268434403328"
                        used: "231638122496"
                email: lemanhcuong6904@gmail.com
                executable: C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: b82aaaad92fadd898cc8b66c11126495140b7aee
                    remote: https://github.com/cuongcuong69/Phan-doan-u-nao-tu-anh-MRI.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-0c327d6f-103f-a828-5173-992f6c06bbbc
                host: LAPTOP-2PI1D10A
                memory:
                    total: "16312721408"
                os: Windows-10-10.0.26100-SP0
                program: D:\Project Advanced CV\trainers\train_uctransnet2d.py
                python: CPython 3.11.9
                root: D:\Project Advanced CV\trainers
                startedAt: "2025-12-29T18:51:20.751834Z"
                writerId: yjtqtwp722ic33neb30i07b9m17vjjhm
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 49
                - 80
                - 105
            "2":
                - 1
                - 49
                - 80
                - 105
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.9
            "5": 0.21.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
AMP:
    value:
        use_amp: true
DEVICE:
    value: cuda
EVAL_EVERY:
    value: 1
EXP_NAME:
    value: uctransnet2d
IMAGE_SIZE:
    value: 256
IN_CHANNELS:
    value: 4
LOSS:
    value:
        W_CE: 1
        W_DICE: 1
MODEL:
    value:
        activation: ReLU
        base_channels: 64
        ctrans_depth: 4
        dropout: 0.1
        img_size: 256
        patch_size:
            - 16
            - 8
            - 4
            - 2
        vis: false
NUM_CLASSES:
    value: 4
NUM_WORKERS_TEST:
    value: 4
NUM_WORKERS_TRAIN:
    value: 4
NUM_WORKERS_VAL:
    value: 4
OPTIM:
    value:
        BETAS:
            - 0.9
            - 0.999
        LR: 0.0005
        MAX_EPOCH: 30
        WEIGHT_DECAY: 0.0001
RESUME_CKPT:
    value: ""
RESUME_WEIGHTS:
    value: ""
RESUME_WEIGHTS_STRICT:
    value: false
SAVE_EVERY:
    value: 5
SCHED:
    value:
        MIN_LR: 1e-06
        WARMUP_EPOCHS: 3
SEED:
    value: 2025
TEST_BATCH:
    value: 8
TRAIN_BATCH:
    value: 8
VAL_BATCH:
    value: 8
WANDB:
    value:
        entity: null
        project: brats2020-uctransnet2d
        use_wandb: true
