_wandb:
    value:
        cli_version: 0.21.1
        e:
            p33mda0dbbmqg2f0c9w3sqneathr9p4t:
                codePath: trainers\train_swin_unet_3d.py
                codePathLocal: train_swin_unet_3d.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "268434403328"
                        used: "230506663936"
                email: lemanhcuong6904@gmail.com
                executable: C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: b82aaaad92fadd898cc8b66c11126495140b7aee
                    remote: https://github.com/cuongcuong69/Phan-doan-u-nao-tu-anh-MRI.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-0c327d6f-103f-a828-5173-992f6c06bbbc
                host: LAPTOP-2PI1D10A
                memory:
                    total: "16312721408"
                os: Windows-10-10.0.26100-SP0
                program: D:\Project Advanced CV\trainers\train_swin_unet_3d.py
                python: CPython 3.11.9
                root: D:\Project Advanced CV\trainers
                startedAt: "2025-12-29T05:15:29.625581Z"
                writerId: p33mda0dbbmqg2f0c9w3sqneathr9p4t
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.9
            "5": 0.21.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
AMP:
    value:
        grad_clip_norm: 1
        use_amp: true
DEVICE:
    value: cuda
EVAL_EVERY:
    value: 1
EXP_NAME:
    value: brats3d_swinunet3d_sup_fullvolume_warmup_cosine
LOSS:
    value:
        loss_type: dicece
        w_ce: 1
        w_dice: 1
NUM_CHANNELS:
    value: 4
NUM_CLASSES:
    value: 4
NUM_WORKERS_TRAIN:
    value: 4
NUM_WORKERS_VAL:
    value: 4
OPTIM:
    value:
        BETAS:
            - 0.9
            - 0.999
        LR: 0.0006
        MAX_EPOCH: 200
        WEIGHT_DECAY: 0.0001
RESUME_CKPT:
    value: ""
SAVE_EVERY:
    value: 1000
SCHED:
    value:
        min_lr: 1e-06
        use: true
        warmup_epochs: 15
SEED:
    value: 2025
SWIN_UNET3D:
    value:
        in_chans: 4
        num_classes: 4
        patch_size:
            - 2
            - 4
            - 4
        window_size:
            - 4
            - 8
            - 8
TRAIN_BATCH:
    value: 1
VAL_BATCH:
    value: 1
VOLUME_SIZE:
    value:
        - 128
        - 128
        - 128
WANDB:
    value:
        entity: null
        project: brats2020-swinunet3d-sup-fullvolume
        use_wandb: true
